//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledHoliday
    {
        public int ScheduledHolidayId { get; set; }
        public System.DateTime HolidayStart { get; set; }
        public System.DateTime HolidayEnd { get; set; }
        public string UserEmail { get; set; }
        public string Reason { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
    }
}
