//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sheet
    {
        public Sheet()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int SheetId { get; set; }
        public System.DateTime DateStarted { get; set; }
        public string ApprovedDays { get; set; }
        public string Email { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
