//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public SystemUser()
        {
            this.CasualHolidays = new HashSet<CasualHoliday>();
            this.ScheduledHolidays = new HashSet<ScheduledHoliday>();
            this.Sheets = new HashSet<Sheet>();
        }
    
        public System.Guid UserId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool Admin { get; set; }
        public string Mobile { get; set; }
        public System.DateTime LastLogin { get; set; }
    
        public virtual ICollection<CasualHoliday> CasualHolidays { get; set; }
        public virtual ICollection<ScheduledHoliday> ScheduledHolidays { get; set; }
        public virtual ICollection<Sheet> Sheets { get; set; }
    }
}
